[model_providers.bigmodel]
name = "z.ai - by BigModel"
# The path `/chat/completions` will be amended to this URL to make the POST
# request for the chat completions.
base_url = "https://open.bigmodel.cn/api/paas/v4"

# Make sure to configure BIGMODEL_API_KEY env variable in your shell.
env_key = "BIGMODEL_API_KEY"

[profiles.zai]
model = "glm-4.5-air"
model_provider = "bigmodel"
