#
# Machines
#

Host dragon
    HostName 172.31.33.12  # dragon.home.swanpan.com

Host dinosaur
    HostName 172.31.33.37  # dinosaur.home.swanpan.com

Host raptor
    HostName 172.31.33.39  # raptor.home.swanpan.com

Host pomelo
    HostName 172.31.33.35  # pomelo.home.swanpan.com

Host pterosaur
    HostName 172.31.33.38  # pterosaur.home.swanpan.com

Host mango
    HostName 172.31.33.34  # mango.home.swanpan.com

Host phoenix
    HostName 172.31.33.36  # phoenix.home.swanpan.com

#
# Routers
#

Host soda
    HostName 192.168.253.32
    User root
    SetEnv TERM=xterm-256color

Host alcohol
    HostName 192.168.253.48
    User root
    SetEnv TERM=xterm-256color

Host fidodido
    HostName 192.168.253.64
    User root
    SetEnv TERM=xterm-256color

Host brandy
    HostName 192.168.253.80
    User root
    SetEnv TERM=xterm-256color

Host fanta
    HostName 192.168.253.96
    User root
    SetEnv TERM=xterm-256color

Host whisky
    HostName 192.168.253.112
    User root
    SetEnv TERM=xterm-256color

Host sprite
    HostName 192.168.253.128
    User root
    SetEnv TERM=xterm-256color

Host mirinda
    HostName 192.168.253.144
    User root
    SetEnv TERM=xterm-256color

Host vodka
    HostName 192.168.253.160
    User root
    SetEnv TERM=xterm-256color

Host tequila
    HostName 192.168.253.176
    User root
    SetEnv TERM=xterm-256color

#
# Proxmox
#

Host citrus
    HostName 172.31.33.252  # citrus.home.swanpan.com
    User root

Host pitaya
    HostName 172.31.33.242  # pitaya.home.swanpan.com
    User root

Host cherry
    HostName 172.31.33.241  # cherry.home.swanpan.com
    User root
