#
# Routers
#

Host soda
    HostName 192.168.253.32
    User root
    SetEnv TERM=xterm-256color

Host alcohol
    HostName 192.168.253.19
    User ubnt
    SetEnv TERM=xterm-256color

Host whisky
    HostName 192.168.253.23
    User ubnt
    SetEnv TERM=xterm-256color

Host brandy
    HostName 192.168.253.80
    User root
    SetEnv TERM=xterm-256color

Host fanta
    HostName 192.168.253.13
    User ubnt
    SetEnv TERM=xterm-256color

Host fidodido
    HostName 192.168.253.64
    User root
    SetEnv TERM=xterm-256color

Host sprite
    HostName 192.168.253.128
    User root
    SetEnv TERM=xterm-256color

#
# Proxmox
#

Host citrus
    HostName 172.31.33.252  # citrus.home.swanpan.com
    User root

Host pitaya
    HostName 172.31.33.242  # pitaya.home.swanpan.com
    User root

Host cherry
    HostName 172.31.33.241  # cherry.home.swanpan.com
    User root
